name: update-data

permissions:
  contents: write   # リポジトリの内容への書き込み権限を付与

on:
  schedule:
    - cron: "0 23 * * *" # 毎日UTC 9:00（日本時間18:00）に実行
  workflow_dispatch: # 手動トリガーも可能

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          # push する場合は、下記を false にする
          persist-credentials: false

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install axios dayjs

      - name: Update data.json
        run: node updateData.js
        env:
          CR_API_TOKEN: ${{ secrets.CR_API_TOKEN }}
          PLAYER_TAG: "#Q9U980QJG" # 自分のプレイヤータグ(先頭#含む)

      - name: Configure git for pushing
        run: |
          # コミット用のユーザ名・メールをセット
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          # リモートURLを x-access-token:${{ secrets.GITHUB_TOKEN }} 形式に書き換え
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Commit changes
        run: |
          git add data.json
          # 変更が無い場合のエラー回避策として || echo を追加
          git commit -m "Update data.json" || echo "No changes to commit"
          # 現在のブランチにPushする
          git push origin HEAD:${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
